openapi: 3.0.0
info:
  version: 1.0.0
  title: Cat list
  description: >-
    This is an OpenAPI Specification created by oas-wizard
    (https://github.com/pafmon/oas-wizard)  
  contact:
    name: PabloFM
    email: pablofm@us.es
    url: 'http://www.isa.us.es'
  license:
    name: MIT
    url: 'http: //opensource.org/licenses/MIT'
paths:
  /api/v1/cats:
    get:
      description: Returns all cats
      operationId: getCats
      responses:
        '200':
          description: Cat List
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/cat'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
    post:
      description: Creates a new cat
      operationId: addCat
      responses:
        '201':
          description: cat created
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
      requestBody:
        x-name: cat
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/cat'
        description: Cat to be created
        required: true
  '/api/v1/cats/{id}':
    get:
      description: Returns a cat by id
      operationId: findCatByid
      parameters:
        - name: id
          in: path
          description: id of cat to fetch
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Cat returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cat'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
    delete:
      description: deletes a single cat based on the id
      operationId: deleteCat
      parameters:
        - name: id
          in: path
          description: ID of cat to delete
          required: true
          schema:
            type: string
      responses:
        '204':
          description: cat deleted
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
    put:
      description: Update a cat based on its id
      operationId: updateCat
      parameters:
        - name: id
          in: path
          description: ID of cat to put
          required: true
          schema:
            type: string
      responses:
        '204':
          description: cat updated
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
      requestBody:
        x-name: cat
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/cat'
        description: Cat to be updated
        required: true
components:
  schemas:
    errorModel:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    cat:
      description: ''
      type: object
      properties:
        id:
          type: number
        name:
          type: string
          minLength: 1
        breed:
          type: string
          minLength: 1
        age:
          type: number
      required:
        - id
        - name
        - breed
        - age
