language: node_js

node_js:
  - "8"

sudo: required

services:
  - docker
  - mongodb

script:
  - npm start
  - npm test 

after_success:
  - REGEXP="release\s[0-9]+\.[0-9]+\.[0-9]+";
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && [[ "$TRAVIS_COMMIT_MESSAGE" =~ $REGEXP ]]; then
    grunt build;
    fi
 