@ECHO OFF
ECHO SETTING ENV VARS FOR RELEASE MANAGER...
ECHO ----------------------------------

ECHO SETTING GITHUB_ACCESS_TOKEN...
SET GITHUB_ACCESS_TOKEN=foo

ECHO SETTING GITHUB_REPO...
SET GITHUB_REPO=isa-group/foo

ECHO SETTING GITHUB_USERNAME...
SET GITHUB_USERNAME=foo

ECHO SETTING DOCKER_HUB_EMAIL...
SET DOCKER_HUB_EMAIL=foo@foo.foo

ECHO SETTING DOCKER_HUB_USERNAME...
SET DOCKER_HUB_USERNAME=foo

ECHO SETTING DOCKER_HUB_PASSWORD...
SET DOCKER_HUB_PASSWORD=foo

ECHO ----------------------------------
ECHO NOW YOU CAN EXECUTE 'grunt release' and 'grunt deliver' commands.
EXIT 0